// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Amount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Lamport       int32                  `protobuf:"varint,2,opt,name=lamport,proto3" json:"lamport,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Amount) Reset() {
	*x = Amount{}
	mi := &file_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Amount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amount) ProtoMessage() {}

func (x *Amount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amount.ProtoReflect.Descriptor instead.
func (*Amount) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

func (x *Amount) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Amount) GetLamport() int32 {
	if x != nil {
		return x.Lamport
	}
	return 0
}

func (x *Amount) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outcome       string                 `protobuf:"bytes,1,opt,name=outcome,proto3" json:"outcome,omitempty"` //fail, success or exception
	Lamport       int32                  `protobuf:"varint,2,opt,name=lamport,proto3" json:"lamport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *Ack) GetLamport() int32 {
	if x != nil {
		return x.Lamport
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lamport       int32                  `protobuf:"varint,1,opt,name=lamport,proto3" json:"lamport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{2}
}

func (x *Empty) GetLamport() int32 {
	if x != nil {
		return x.Lamport
	}
	return 0
}

type Outcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HighestBid    int32                  `protobuf:"varint,2,opt,name=highestBid,proto3" json:"highestBid,omitempty"`
	ActionClosed  bool                   `protobuf:"varint,3,opt,name=actionClosed,proto3" json:"actionClosed,omitempty"`
	Lamport       int32                  `protobuf:"varint,4,opt,name=lamport,proto3" json:"lamport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outcome) Reset() {
	*x = Outcome{}
	mi := &file_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outcome) ProtoMessage() {}

func (x *Outcome) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outcome.ProtoReflect.Descriptor instead.
func (*Outcome) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{3}
}

func (x *Outcome) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Outcome) GetHighestBid() int32 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *Outcome) GetActionClosed() bool {
	if x != nil {
		return x.ActionClosed
	}
	return false
}

func (x *Outcome) GetLamport() int32 {
	if x != nil {
		return x.Lamport
	}
	return 0
}

var File_proto_proto protoreflect.FileDescriptor

const file_proto_proto_rawDesc = "" +
	"\n" +
	"\vproto.proto\"J\n" +
	"\x06Amount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\alamport\x18\x02 \x01(\x05R\alamport\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\"9\n" +
	"\x03Ack\x12\x18\n" +
	"\aoutcome\x18\x01 \x01(\tR\aoutcome\x12\x18\n" +
	"\alamport\x18\x02 \x01(\x05R\alamport\"!\n" +
	"\x05Empty\x12\x18\n" +
	"\alamport\x18\x01 \x01(\x05R\alamport\"w\n" +
	"\aOutcome\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1e\n" +
	"\n" +
	"highestBid\x18\x02 \x01(\x05R\n" +
	"highestBid\x12\"\n" +
	"\factionClosed\x18\x03 \x01(\bR\factionClosed\x12\x18\n" +
	"\alamport\x18\x04 \x01(\x05R\alamport2;\n" +
	"\aAuction\x12\x14\n" +
	"\x03Bid\x12\a.Amount\x1a\x04.Ack\x12\x1a\n" +
	"\x06Result\x12\x06.Empty\x1a\b.OutcomeB\x10Z\x0eHW5/grpc/protob\x06proto3"

var (
	file_proto_proto_rawDescOnce sync.Once
	file_proto_proto_rawDescData []byte
)

func file_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)))
	})
	return file_proto_proto_rawDescData
}

var file_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_proto_goTypes = []any{
	(*Amount)(nil),  // 0: Amount
	(*Ack)(nil),     // 1: Ack
	(*Empty)(nil),   // 2: Empty
	(*Outcome)(nil), // 3: Outcome
}
var file_proto_proto_depIdxs = []int32{
	0, // 0: Auction.Bid:input_type -> Amount
	2, // 1: Auction.Result:input_type -> Empty
	1, // 2: Auction.Bid:output_type -> Ack
	3, // 3: Auction.Result:output_type -> Outcome
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_proto_init() }
func file_proto_proto_init() {
	if File_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_depIdxs,
		MessageInfos:      file_proto_proto_msgTypes,
	}.Build()
	File_proto_proto = out.File
	file_proto_proto_goTypes = nil
	file_proto_proto_depIdxs = nil
}
